### ISSUE TITLE
[Feature Request] Use a bundling service

### ISSUE THREAD

**Issue by L1lith** [neplextech/canvacord#97]
**Is your feature request related to a problem? Please describe.**
The library bundle is very large. Bundling makes the total payload significantly smaller, and you can include a source map if you wish.

**Describe the solution you'd like**
I strongly recommend [microbundle](https://www.npmjs.com/package/microbundle), but it depends on what you're looking for in a bundler.

**Describe alternatives you've considered**
Webpack & rollup are both good alternatives.

**Comment by Nicholaiii** [comment]
Bundling is almost entirely irrelevant for backend.
If you really wanted to save space on this dependency, consider a solution that allows it to move away from Moment.js, which is a legacy dep that is no longer being developed on and whose maintainers suggest not using it; dayjs is an excellent alternative
![image](https://user-images.githubusercontent.com/7280931/126529544-db034ad4-733d-45d7-8289-42c89904db0c.png)

**Comment by DevAndromeda** [comment]
Also would like to bundle .d.ts into single file 😁

**Comment by rhygg** [comment]
The v6 update will probably fix the size issue. We're implementing packaging all the different stacks of modules into mono-repos, so that they are independent of each other, significantly decreasing the size of the main package. 
Each mono-repo will be distributed into namely "plugins" and can be used by users only when they download the "plugin".
Dependencies although, are symlink(ed) into all the packages. This shouldn't be an issue unless we have too many external dependencies.
